### ISSUE TITLE
paste in neovim over mosh adds extra indentation

### ISSUE THREAD

**Issue by albertnetymk** [keithw/mosh#631] opened 2015-06-12 20:40 UTC
## How to reproduce the problem
1. Connect to the server using: `mosh <server-ip> --server="LC_CTYPE=en_US.UTF-8 mosh-server"`
2. Open neovim using `nvim -u NONE dummy.py`
3. `:filetype plugin indent on`
4. `:set filetype=python`
5. Go to insert mode and paste the following snippet into neovim using right-click, then select `paste`:
```
x = 1
if x == 1:
    # indented four spaces
    print "x is 1."
```
The result looks like this:
```
x = 1
if x == 1:
        # indented four spaces
            print "x is 1."
```
Tried ssh instead of mosh, and the above procedures create the right indentation, expected behavior.

## ENV:
mosh: 1.2.4
Client: OSX 10.9.5
Server: XUbuntu 14.04

**Comment by andersk** [comment] 2015-06-12 20:49
Duplicate of #430 (fixed in Git for the upcoming 1.2.5 release).

**Closed by andersk** 2015-06-12 20:49 UTC
