### ISSUE TITLE
Blinking text with ls --color=auto?

### ISSUE THREAD

**Issue by PaBLoX-CL** [keithw/mosh#500] opened 2014-02-09 03:30 UTC
I just started to try mosh, and I found something weird, running `ls --color=auto` results in a weird colored blinking text. Any other tools (like vim and tmux for ie), seems to work fine. I have been searching, but I can't seem to find any reference to this issue. Any clue what could be causing it?

**Comment by chr4** [comment] 2015-04-28 15:07
+1

**Comment by chr4** [comment] 2015-04-28 15:24
I think I found the issue:
When using tmux/ screen, the terminals `TERM` variable is `screen-256color` instead of `xterm-256color`. When using `export TERM=xterm-256color`, it works from inside tmux as well as without tmux.

This seems to be known, as there's a section in the README: https://github.com/keithw/mosh/blob/50152bfcba872dd2ef5318877823005ad0c4593f/macosx/readme.rtf#L69-L75

When setting `TERM=screen-256color-bce` it also works fine.

Setting the following option in tmux helps:
```
set-option -g default-terminal "screen-256color-bce"
```

**Comment by cgull** [comment] 2015-06-06 18:00
@PaBLoX-CL, your issue is almost certainly fixed by #507-- the dircolors file you link to has the issue that's fixed in that PR.  If you want, please try building and installing mosh from the master branch here, on both client and server.  I think you'll find your problem fixed.  Closing this issue for now.

@chr4, no, that code (and the similar code in mosh-server.cc, which is what's really relevant) is correct.  Mosh is a virtual terminal emulator in its own right, just as screen/tmux are, and must set TERM=xterm, which is the terminal it most closely resembles.

**Closed by cgull** 2015-06-06 18:00 UTC

**Comment by timofonic** [comment] 2016-02-11 17:07
@PaBLoX-CL 

Can you confirm the issue is fixed these days? Please, I would like to be sure before having issues with MOSH.

**Comment by keithw** [comment] 2016-02-11 17:39
The issue is closed because we believe it is solved. If you use mosh and find a problem, please open a new issue.
