### ISSUE TITLE
Mosh fails at rendering formatting with 256 colors

### ISSUE THREAD

**Issue by DanielBaulig** [keithw/mosh#599] opened 2015-04-25 22:43 UTC
# echo -e "\e[38;05;124mTEST\e[0m"

Outputs red TEST

    # echo -e "\e[01;38;05;124mTEST\e[0m"

Outputs white TEST on grey background. Reproduces for all formatting options with 256 color palette colors. Does not reproduce when using 16 color palette.

Running mosh 1.2.4 from Arch Linux repository.
Note: I am running mosh inside of tmux. tmux is run with `tmux -2`. TERM is set to xterm-256color via `TERM=xterm-256color mosh remote-host`

**Comment by andersk** [comment] 2015-04-25 22:54
Duplicate of #282.

**Closed by andersk** 2015-04-25 22:54 UTC
