### ISSUE TITLE
Escape codes that change color don't work properly

### ISSUE THREAD

**Issue by pankdm** [keithw/mosh#507] opened 2014-03-24 17:11 UTC
It seems like mosh doesn't support escape sequences that contain both foreground and background color changes (see http://en.wikipedia.org/wiki/ANSI_escape_code#Colors).
The following command isn't shown correctly in mosh:
```
echo -e "\033[38;5;1;48;5;220m Some text\033[m"
```
wheres in usual terminal (say `iterm2`) it looks fine (red text on yellow background).

Note, that the individual color changing commands, e.g:
```
 echo -e "\033[38;5;1m Some text\033[m"
```
and
```
echo -e "\033[48;5;220m Some text\033[m"
```
works fine.

P.S. If it helps: `$TERM` is `xterm-256color`

**Comment by cgull** [comment] 2015-06-06 17:45
Fix merged.

**Closed by cgull** 2015-06-06 17:45 UTC

**Comment by cgull** [comment] 2015-06-06 18:14
Sorry, @keithw, but I think this is the right thing to do.  Terminfo/termcap were never intended as complete descriptions of terminal behavior; they're just databases that curses/terminfo can refer to to figure out what they should do.  All of the other emulator code I've looked at (I think there were at least 3: xterm, gnome-terminal, rxvt maybe?) works this way.

**Comment by timofonic** [comment] 2016-02-11 17:10
@pankdm @cgull 

Is this finally solved? (sorry for asking in different issues, not sure where to ask...)

**Comment by keithw** [comment] 2016-02-11 17:39
The issue is closed because it is solved. If you use mosh and find a problem, please open a new issue.
